const router = require('express').Router();
const c = require('../controllers/personController');
const { protect } = require('../middleware/auth');
router.use(protect);
router.get('/',    c.getAll);
router.post('/',   c.create);
router.get('/:id', c.getOne);
router.put('/:id', c.update);
router.delete('/:id', c.delete);
module.exports = router;
