const router = require('express').Router();
const c = require('../controllers/villageController');
const { protect } = require('../middleware/auth');
router.use(protect);
router.get('/', c.getAll);
router.get('/export', c.exportExcel);
router.get('/statement/:personName', c.getPersonStatement);
router.post('/', c.addTransaction);
router.delete('/:id', c.delete);
module.exports = router;
